### PR TITLE
Some UI changes

### PR DESCRIPTION
**Pull request by ztimms73**
What changes were made:
- The Toolbar is now in the MaterialCardView and is similar to the persistent search bar (https://material.io/design/navigation/search.html#persistent-search)
- Items in NavigationView are now made according to MD rules (https://material.io/components/navigation-drawer#specs)
- Improved empty states (https://material.io/design/communication/empty-states.html#content)
- Fixed spelling errors in the strings for the Russian language, namely in the strings `you_have_not_favourites_yet` and `text_history_holder_primary` (ex. `text_history_holder`)

| Search | Local | Favourite | History | Feed |
| --- | --- | --- | --- | --- |
| Screenshot_1624209277 | Screenshot_1624207252 | Screenshot_1624207266 | Screenshot_1624207271 | Screenshot_1624207273 |

### CODE REVIEW

**Comment by nv95** [comment]
Cool.
I think, search view should be always expanded and placed instead of title (like in Google Play). But where to show title of the current screen?

**Comment by ztimms73** [comment]
@nv95, looks like [this](https://drive.google.com/file/d/1OYJzpaJSOZ8tkhWx4rlO0QF5CErCf64_/view?usp=sharing)? I just added a SearchView to the Toolbar and this is what came out. About title in the toolbar is an interesting question, I also think how to implement it better. But I can say that the string "Search manga" also looks appropriate.

**Comment by ztimms73** [comment]
Improved handling when clicking on SearchView, but now how do I take text from a search query and move it to SearchView?
https://drive.google.com/file/d/15X4M4Us4IDF8nadXXw_RreYmj-iYVhWo/view?usp=sharing

**Comment by nv95** [comment]
> looks like [this](https://drive.google.com/file/d/1OYJzpaJSOZ8tkhWx4rlO0QF5CErCf64_/view?usp=sharing)?

Yes

> text from a search query and move it to SearchView

see `SearchSuggestionListener.onQueryClick`

**Review by nv95 — APPROVED** [review]

**Pull request merged**
